name: FastAPI CI Pipeline

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Login to docker hub
                run: echo "${{ secrets.DOCKERTOKEN }}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin

            -   name: Build docker image
                run:  docker build -t ikhramfahrezi/my-fastapi-app:latest .

            -   name: push to docker hub
                run:  docker push ikhramfahrezi/my-fastapi-app:latest

            -   name: Deploy to AWS EC2 via SSH
                uses: appleboy/ssh-action@v1.0.0
                with:
                    host: ${{ secrets.EC2_HOST }}
                    username: ${{ secrets.EC2_USERNAME }}
                    key: ${{ secrets.EC2_SSH_KEY }}
                    script: |
                        cd /home/ubuntu
                        sudo docker-compose pull
                        sudo docker-compose up -d